version: "3.8"

services:
    mongodb:
        container_name: mongodb
        build:
            context: ./
            dockerfile: ./mongodb/mongodb.Dockerfile
        ports:
            - 8082:27017
        environment:
            username: admin
            password: password
            databaseName: primaryDB
