export type Patient = {
    schemaVersion: number,
    _id?: string,
    socialId: number,
    firstName?: string,
    lastName?: string,
    gender?: 'male' | 'female',
    age?: number,
    birthDate?: number,
    documentsIds: string[] = [],
    medicalHistory: string[] = [],
    diagnosis: string[] = [],
    visitDues?: number[],
    address?: string,
    createdAt?: number,
    updatedAt?: number,
}
