name: Demo

on:
    workflow_dispatch:

    push:
        branches:
            - main

jobs:
    demo:
        runs-on: ubuntu-22.04

        steps:
            -
                uses: appleboy/ssh-action@v1.0.3
                with:
                    host: ${{ secrets.SSH_SERVER_ADDRESS }}
                    port: ${{ secrets.SSH_SERVER_PORT }}
                    username: ${{ secrets.SSH_SERVER_USERNAME }}
                    password: ${{ secrets.SSH_SERVER_PASSWORD }}
                    script: |
                        mkdir -p swarm/clients/Ghorbani/mongodb/data
                        docker stack rm clients_ghorbani_clinic_demo
                        sleep 5s

            -
                uses: hirbod-codes/secret_creator_github_action@v1.2.22
                with:
                    swarm-secrets-prefix: 'SWARM_'
                    ssh-server-address: ${{ secrets.SSH_SERVER_ADDRESS }}
                    ssh-server-port: ${{ secrets.SSH_SERVER_PORT }}
                    ssh-server-username: ${{ secrets.SSH_SERVER_USERNAME }}
                    ssh-server-password: ${{ secrets.SSH_SERVER_PASSWORD }}
                    secrets-json: ${{ toJson(secrets) }}

            -
                uses: actions/checkout@v4
        
            -
                uses: appleboy/scp-action@v0.1.7
                with:
                    host: ${{ secrets.SSH_SERVER_ADDRESS }}
                    port: ${{ secrets.SSH_SERVER_PORT }}
                    username: ${{ secrets.SSH_SERVER_USERNAME }}
                    password: ${{ secrets.SSH_SERVER_PASSWORD }}
                    source: "./demo.yml"
                    target: ~/swarm/clients/Ghorbani/

            -
                uses: appleboy/ssh-action@v1.0.3
                with:
                    host: ${{ secrets.SSH_SERVER_ADDRESS }}
                    port: ${{ secrets.SSH_SERVER_PORT }}
                    username: ${{ secrets.SSH_SERVER_USERNAME }}
                    password: ${{ secrets.SSH_SERVER_PASSWORD }}
                    script: |
                        cd swarm/clients/Ghorbani/
                        docker image rm -f ghcr.io/hirbod-codes/demo_proxy/demo_proxy:latest
                        docker stack rm clients_ghorbani_clinic_demo
                        hostIpAddress=${{ secrets.SSH_SERVER_ADDRESS }} docker stack deploy --detach=true --with-registry-auth -c demo.yml clients_ghorbani_clinic_demo

